---
# yaml-language-server: $schema=https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
name: ecls
description: Editorconfig Language Server
homepage: https://github.com/Lilja/ecls
licenses:
  - proprietary
languages:
  - editorconfig
categories:
  - LSP

source:
  id: pkg:npm/ecls@0.0.3

bin:
  ecls: npm:ecls
