---
# yaml-language-server: $schema=https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
name: redocly-language-server
description: Redocly VS Code extension
homepage: https://github.com/Redocly/redocly-vs-code
licenses:
  - proprietary
languages:
  - openapi
categories:
  - LSP

source:
  id: pkg:openvsx/Redocly/openapi-vs-code@0.12.14
  download:
    file: Redocly.openapi-vs-code-{{version}}.vsix

bin:
  redocly-ls: node:extension/out/server/src/server.js

neovim:
  lspconfig: redocly_ls
