---
# yaml-language-server: $schema=https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
name: plantuml-lsp
description: Language Server for PlantUML
homepage: https://github.com/ptdewey/plantuml-lsp
licenses:
  - MIT
languages:
  - plantuml
categories:
  - LSP

source:
  id: pkg:golang/github.com/ptdewey/plantuml-lsp@v0.5.3

bin:
  plantuml-lsp: plantuml-lsp

neovim:
  lspconfig: plantuml_lsp
