---
# yaml-language-server: $schema=https://github.com/mason-org/registry-schema/releases/latest/download/package.schema.json
name: atlas-community
description: Declarative schema migrations with schema-as-code workflows
homepage: https://atlasgo.io
licenses:
  - Apache-2.0
languages:
  - HCL
  - Go
categories:
  - Runtime

source:
  # renovate:datasource=github-releases
  id: pkg:generic/ariga:atlas@1.2.0
  download:
    - target: win_x64
      files:
        atlas: https://release.ariga.io/atlas/atlas-community-windows-amd64-v{{version}}.exe
      ext: .exe
    - target: linux_x64
      files:
        atlas: https://release.ariga.io/atlas/atlas-community-linux-amd64-v{{version}}
    - target: linux_arm64
      files:
        atlas: https://release.ariga.io/atlas/atlas-community-linux-arm64-v{{version}}
    - target: darwin_x64
      files:
        atlas: https://release.ariga.io/atlas/atlas-community-darwin-amd64-v{{version}}
    - target: darwin_arm64
      files:
        atlas: https://release.ariga.io/atlas/atlas-community-darwin-arm64-v{{version}}

bin:
  atlas: atlas{{source.download.ext}}
